### ISSUE TITLE
Output score instead of type

### ISSUE THREAD

**Issue by Forest216** [adobe/stringlifier#14]
Is there a way to output the score of prediction results instead of the direct output type？

**Comment by tiberiu44** [comment]
Hi @Forest216 ,

Sorry for the late reply. It's currently not possible, due to the model's architecture:

Tagging happens at character level, than it gets decoded (maximum spans of the same token type). Given that we have a different score for each character, I don't know how an aggregated score (at token level) should look like. If you have any suggestion, maybe we could try something.

Best,
Tiberiu

**Comment by Forest216** [comment]
Hi @tiberiu44,
Sorry for the late reply,too.Thank you for your answer.I will continue to study.
Thank you for your project.

Best,
Forest
